services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: geoecoreport-app
    container_name: geoecoreport-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - geoeco-network

  db:
    image: mysql:8.0
    container_name: geoecoreport-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: geoecoreport
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - geoeco-network

networks:
  geoeco-network:
    driver: bridge

volumes:
  mysql_data: