services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: geoecoreport-app

    container_name: geoecoreport-app

    restart: unless-stopped

    tty: true

    working_dir: /var/www

    ports:
      - "8000:8000"

    volumes:
      - .:/var/www

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: geoecoreport
      DB_USERNAME: root
      DB_PASSWORD: root

    depends_on:
      db:
        condition: service_healthy

    networks:
      - geoeco-network


  db:
    image: mysql:8.0

    container_name: geoecoreport-db

    restart: unless-stopped

    tty: true

    ports:
      - "3308:3306"

    environment:
      MYSQL_DATABASE: geoecoreport
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot"
        ]

      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - geoeco-network


networks:

  geoeco-network:
    driver: bridge


volumes:

  mysql_data: